version: '3'

includes:
  docker: ./taskfiles/Taskfile_docker.yml

tasks:

  default:
    silent: true
    cmds:
      - task --list-all
            
  build:
    cmds:
      - go build -v main.go
      - go build -o dare-db-app main.go

  mod-tidy:
    aliases: [gmt, tidy]
    silent: true
    cmds:
       - go mod tidy

  run:
    aliases: [r]
    env:
        DARE_HOST: 127.0.0.1
    cmds:
      - go run main.go

  run-watch:
    aliases: [rw]
    env:
        DARE_HOST: 127.0.0.1
    cmds:
      - wgo -xdir data go run main.go
      
  test:
    aliases: [t]
    cmds:
      - go test ./... -v
  
  pre-commit-run:
    aliases: [pcr]
    silent: true
    run: once
    cmds:
      - lefthook run pre-commit --all-files
 